import {
  BookOpen,
  Brain,
  Code2,
  Compass,
  Dices,
  Filter,
  FlaskConical,
  Gamepad2,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Layers,
  Leaf,
  Lightbulb,
  Megaphone,
  Palette,
  PenLine,
  Presentation,
  Puzzle,
  Rocket,
  ShieldCheck,
  Sparkles,
  Trophy,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  BookOpen,
  Brain,
  Code2,
  Compass,
  Dices,
  Filter,
  FlaskConical,
  Gamepad2,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Layers,
  Leaf,
  Lightbulb,
  Megaphone,
  Palette,
  PenLine,
  Presentation,
  Puzzle,
  Rocket,
  ShieldCheck,
  Sparkles,
  Trophy,
  Users,
  Wrench,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = iconMap[name] ?? Sparkles;
  return <Cmp className={className} aria-hidden="true" />;
}